In [43]:
# How To Build a Deep Learning Model to Predict Employee Retention Using Keras and TensorFlow.
# The author selected Girls Who Code to receive a donation as part of the Write for DOnations program.
#  will predict the probability of an employee leaving a company. Retaining the best employees is an 
#important factor for most organizations. 

import pandas as pd
import numpy as np

In [44]:
df= pd.read_csv("https://raw.githubusercontent.com/mwitiderrick/kerasDO/master/HR_comma_sep.csv")

In [47]:
df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [77]:
# Convert Categorical columns to Numbers. You do this by converting them to dummy variables. Dummy variables are usually ones and zeros that indicate the presence or absence of a categorical feature. In this kind of situation, 
#you also avoid the dummy variable trap by dropping the first dummy.
feats = ['department','salary']
df_final = pd.get_dummies(df, columns=feats,drop_first=True)

In [ ]:
# STEP 2 — Separating Your Training and Testing Datasets

In [49]:
## Separating Training and Test dataset
from sklearn.model_selection import train_test_split

In [50]:
# dropping the "left Column". Your deep learning model expects to get the data as arrays. Therefore you use numpy 
## to convert the data to numpy arrays with the .values attribute.
X = df_final.drop(['left'],axis=1).values
X

array([[0.38, 0.53, 2.  , ..., 0.  , 1.  , 0.  ],
       [0.8 , 0.86, 5.  , ..., 0.  , 0.  , 1.  ],
       [0.11, 0.88, 7.  , ..., 0.  , 0.  , 1.  ],
       ...,
       [0.37, 0.53, 2.  , ..., 0.  , 1.  , 0.  ],
       [0.11, 0.96, 6.  , ..., 0.  , 1.  , 0.  ],
       [0.37, 0.52, 2.  , ..., 0.  , 1.  , 0.  ]])

In [51]:
y = df_final['left'].values
y

array([1, 1, 1, ..., 1, 1, 1])

In [53]:
# keeping test data as 30 % of total data
X_train, X_test,y_train, y_test = train_test_split(X,y, test_size=0.3)
#You'll pass this data to the keras model after converting it into numpy arrays

In [76]:
# Transforming the dataset. Scaling is important to keep the dataset more efficient.Scaling dataset using 
# STANDARDSCALER will ensure Mean=0 and  a unit variable or standard deviation 1. Standard Sclaer transforms 
# the data normally distributed. it will Scale the features within same range. This is imp bcz we are 
# comparing fetaures having different measurements

In [ ]:
## STEP 3 — Transforming the Data

In [55]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()     # calling and instance of Scnadard Scaler()
X_train = sc.fit_transform(X_train)   # fir_tranform to scale the training and test set
X_test = sc.transform(X_test)

In [56]:
# STEP 4 — Building the Artificial Neural NetworkBUILDING ARTIFICIAL NETWORK

In [57]:
# From keras, you'll then import the Sequential module to initialize the artificial neural network. An artificial neural network is a computational model that 
#is built using inspiration from the workings of the human brain. You'll import the Dense module as well, which will add layers to your deep learning model.

#When building a deep learning model you usually specify three layer types:

#The input layer is the layer to which you'll pass the features of your dataset. There is no computation that occurs in this layer. It serves to pass features to the hidden layers.
#The hidden layers are usually the layers between the input layer and the output layer—and there can be more than one. These layers perform the computations and pass the information to the output layer.
#The output layer represents the layer of your neural network that will give you the results after training your model. It is responsible for producing the output variables.

In [58]:
import keras
# use Sequential to initialize a linear stack of layers(classfier).
from keras.models import Sequential 
# adding layers to classifier using add function
from keras.layers import Dense

In [59]:
classifier= Sequential()  # Initialising the classifier

In [60]:
# 1st Param - No of nodes the NN should have.to find no of nodes is to take average of nodes in input layer & output nodes
## Kernel_Initialiser - When you fit your deep learning model the weights will be initialized to numbers close to zero, but not zero. To achieve this you use the uniform distribution initializer. 
# kernel_initializer is the function that initializes the weights.
# Activation Funcion - Deep Leearning modle will learn through this functn. These are LINEAR and NoN-Linear functns.
# ReLU generalizes well on data
## input_dim - showis no of feartures in your input data
classifier.add(Dense(9, kernel_initializer = "uniform", activation="relu", input_dim=18))

In [62]:
# Adding the output layers which will give us predictions
#  The number of output nodes. You expect to get one output: if an employee leaves the company. 
# Therefore you specify one output node.
# For kernel_initializer you use the sigmoid activation function so that you can get the probability 
# that an employee will leave. In the event that you were dealing with more than two categories, 
# you would use the softmax activation function, which is a variant of the sigmoid activation function.
classifier.add(Dense(1,kernel_initializer = "uniform", activation="sigmoid"))

In [64]:
# Applying Gradient Descent to minimise the cost function as optimize startegy. Here we will use as Adam
classifier.compile(optimizer="Adam", loss="binary_crossentropy", metrics=['accuracy'])

In [75]:
# FiTTING your CLASSIfier to the DATAset using .fit() function
classifier.fit(X_train,y_train, batch_size=10, epochs=1)

Epoch 1/1
10499/10499 [==============================] - 1s 104us/step - loss: 0.4114 - acc: 0.7588


In [ ]:
#STEP5 — Running Predictions on the Test Set

In [72]:
## RUNNING Prediction on your TEST Dataset
y_pred= classifier.predict(X_test)
y_pred

array([[0.20775685],
       [0.20614198],
       [0.24818602],
       ...,
       [0.31802285],
       [0.2166252 ],
       [0.20651561]], dtype=float32)

In [74]:
# keeping Threshold for 50% of employees leaving companies. Creating predictions using the predict method and 
# set the threshold for determining if an employee is likely to leav
y_pred= (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [68]:
## STEP- 6 Checking Confusion Matrix

In [71]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
cm

array([[3461,    0],
       [1039,    0]])

In [78]:
# STEP 7 - Making a single prediction 

In [79]:
new_pred = classifier.predict(sc.transform(np.array([[0.26,0.7,3.0,238.,6.0,0.,0.,0.,0., 0.,0.,0.,0.,0.,1.,0., 0.,1.]])))

In [80]:
new_pred = (new_pred > 0.5)
new_pred

array([[False]])

In [81]:
new_pred = (new_pred > 0.6)
new_pred

array([[False]])

In [82]:
# STEP:8 Improving the Model Accuracy

In [83]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [92]:
def make_classifier():
    classifier = Sequential()
    classifier.add(Dense(9, kernel_initializer = "uniform", activation="relu", input_dim=18))
    classifier.add(Dense(1,kernel_initializer="uniform", activation="sigmoid"))
    classifier.compile(optimizer="adam", loss ="binary_crossentropy", metrics=["accuracy"])
    return classifier

In [93]:
classifier= KerasClassifier(build_fn= make_classifier, batch_size=10, nb_epoch=1)

In [94]:
accuracies = cross_val_score(estimator= classifier , X=X_train, y=y_train, cv=10, n_jobs=-1)

In [96]:
mean= accuracies.mean()
mean

0.830464837285982

In [97]:
variance = accuracies.var()

In [98]:
# STEP 9: Adding dropout Regularization to fight Over-Fitting

In [99]:
# In neural networks, dropout regularization is the technique that fights overfitting by adding a Dropout layer in 
# your neural network. It has a rate parameter that indicates the number of neurons that will deactivate at each iteration. 
# The process of deactivating nerurons is usually random. In this case, you specify 0.1 as the rate meaning that 1% of the neurons will deactivate during the training proc

In [100]:
from keras.layers import Dropout

classifier = Sequential()
classifier.add(Dense(9, kernel_initializer = "uniform", activation = "relu", input_dim=18))
classifier.add(Dropout(rate = 0.1))
classifier.add(Dense(1, kernel_initializer = "uniform", activation = "sigmoid"))
classifier.compile(optimizer= "adam",loss = "binary_crossentropy",metrics = ["accuracy"])


In [101]:
## STEP 10 : HYPERPATAMETER TUNING

In [121]:
from sklearn.model_selection import GridSearchCV
def make_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(9, kernel_initializer = "uniform", activation = "relu", input_dim=18))
    classifier.add(Dense(1, kernel_initializer = "uniform", activation = "sigmoid"))
    classifier.compile(optimizer= optimizer,loss = "binary_crossentropy",metrics = ["accuracy"])
    return classifier

In [122]:
classifier = KerasClassifier(build_fn = make_classifier)

In [123]:
params = {
    'batch_size':[20,35],
    'epochs':[2,3],
    'optimizer':['adam','rmsprop']
}

In [124]:
grid_search = GridSearchCV(estimator=classifier,
                           param_grid=params,
                           scoring="accuracy",
                           cv=2)

In [125]:
grid_search = grid_search.fit(X_train,y_train)

Epoch 1/2
5249/5249 [==============================] - 1s 97us/step - loss: 0.5654 - acc: 0.7620
Epoch 2/2
5249/5249 [==============================] - 0s 44us/step - loss: 0.4120 - acc: 0.7626
Epoch 1/2
5250/5250 [==============================] - 1s 96us/step - loss: 0.5769 - acc: 0.7537
Epoch 2/2
5250/5250 [==============================] - 0s 47us/step - loss: 0.4136 - acc: 0.7771
Epoch 1/2
5249/5249 [==============================] - 0s 87us/step - loss: 0.5714 - acc: 0.7628
Epoch 2/2
5249/5249 [==============================] - 0s 43us/step - loss: 0.4128 - acc: 0.7914
Epoch 1/2
5250/5250 [==============================] - 0s 92us/step - loss: 0.5952 - acc: 0.7530
Epoch 2/2
5250/5250 [==============================] - 0s 42us/step - loss: 0.4412 - acc: 0.7872
Epoch 1/3
5249/5249 [==============================] - 1s 105us/step - loss: 0.5711 - acc: 0.7596
Epoch 2/3
5249/5249 [==============================] - 0s 46us/step - loss: 0.4120 - acc: 0.7853
Epoch 3/3
5249/5249 [========

In [126]:
best_param = grid_search.best_params_
best_accuracy = grid_search.best_score_

In [127]:
best_param

{'batch_size': 35, 'epochs': 3, 'optimizer': 'adam'}

In [128]:
best_accuracy

0.8307457853128869